//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Domain.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAPI.Domain.Resource.EmployeeResource", typeof(EmployeeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng chưa đúng định dạng.
        /// </summary>
        public static string BankAccountNotValid {
            get {
                return ResourceManager.GetString("BankAccountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không thể vượt quá ngày hiện tại..
        /// </summary>
        public static string DateOfBirthNotInFuture {
            get {
                return ResourceManager.GetString("DateOfBirthNotInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh phải thỏa mãn nhân viên trong độ tuổi lao động từ 18 đến 70..
        /// </summary>
        public static string DateOfBirthNotValid {
            get {
                return ResourceManager.GetString("DateOfBirthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được để trống..
        /// </summary>
        public static string DepartmentNameNotEmpty {
            get {
                return ResourceManager.GetString("DepartmentNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không tồn tại. Vui lòng kiểm tra lại tên đơn vị..
        /// </summary>
        public static string DepartmentNotExist {
            get {
                return ResourceManager.GetString("DepartmentNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email phải có định dạng abc@gmail.com với abc là các kí tự bất kì có độ dài bất kì..
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        public static string EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên phải có định dạng NV-00abcd với a,b,c,d là các chữ số tự nhiên..
        /// </summary>
        public static string EmployeeCodeNotValid {
            get {
                return ResourceManager.GetString("EmployeeCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được để trống..
        /// </summary>
        public static string FullNameNotEmpty {
            get {
                return ResourceManager.GetString("FullNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên không được quá 100 kí tự..
        /// </summary>
        public static string FullNameTooLong {
            get {
                return ResourceManager.GetString("FullNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định phải đúng định đạng..
        /// </summary>
        public static string LandLinePhoneNotValid {
            get {
                return ResourceManager.GetString("LandLinePhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại di động phải đúng định dạng..
        /// </summary>
        public static string MobileNotValid {
            get {
                return ResourceManager.GetString("MobileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không thể vượt quá ngày hiện tại..
        /// </summary>
        public static string PICreatedDateNotInFuture {
            get {
                return ResourceManager.GetString("PICreatedDateNotInFuture", resourceCulture);
            }
        }
    }
}
